### ISSUE TITLE
Update Bug, Feature, and PR templates to have a better UI

### ISSUE THREAD

**Issue by pogi7** [opencaesar/oml-vision#79]
## Checklist before submitting a feature request

- [x] I have reviewed [CONTRIBUTING.md](https://github.com/opencaesar/oml-vision/blob/master/CONTRIBUTING.md) document
- [x] I have done a quick search on the issue tracker to check if the feature request is not redundant

## Is your feature request related to a problem? If yes, describe the problem

I am annoyed that the templates don't have a good way to prompt users for information.

## Describe the desired feature

I want to update the bug, feature, and PR templates to have a better UI.

## Additional context

Here's an example for the feature template
```yml
name: 🔧 Feature
description: Create a new feature
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to a file a new feature.  Please provide a description below for it.
  - type: input
    id: os
    attributes:
      label: Operating system
      description: "Which operating system should this be implemented on? Please provide the version as well."
      placeholder: "macOS Sonoma 14.4.1"
    validations:
      required: true  
  - type: input
    id: Software-repo
    attributes:
      label: Software repo
      description: "Please provide the name or link to the software repo where to implement the feature.  "
      placeholder: "Repo here"
    validations:
      required: true
  - type: input
    id: Software-version
    attributes:
      label: Software version
      description: "Please provide the version/branch to implement this feature on.  "
      placeholder: "Version/branch here"
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: Tell me more about the feature?
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use case of the feature
      description: What value does implementing this feature provide?
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Other
      description: If applicable, please provide any other relevant info needed to create the feature.
      render: shell
```

Here's an example for the bug template
```yml
name: 🐛 Bug
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: input
    id: os
    attributes:
      label: Operating system
      description: "Which operating system did this bug occur on? Please provide the version as well."
      placeholder: "macOS Sonoma 14.4.1"
    validations:
      required: true   
  - type: input
    id: Software-repo
    attributes:
      label: Software repo
      description: "Please provide the name or link to the software repo where to implement the feature.  "
      placeholder: "Repo here"
    validations:
      required: true
  - type: input
    id: Software-version
    attributes:
      label: Software version
      description: "Which version/branch of the software is this bug occurring on?"
      placeholder: "Version/branch here"
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: bug-fix
    attributes:
      label: Bug fix
      description: What should be fixed?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Which steps do we need to take to reproduce this error?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant log output.
      render: shell
  - type: textarea
    id: other
    attributes:
      label: Other
      description: If applicable, please provide any other relevant info needed to create the feature.
      render: shell
```

Here's an example for the PR template
```md
## What type of PR is this? (check all applicable)

- [ ] 🔧 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🖥️ Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🔨 Build
- [ ] 🔁 CI
- [ ] 📦 Release
- [ ] ⏪️ Revert

## Description
<!-- Insert description here -->

## Why this change?
<!-- Help provide an explaination for the ticket -->


## Related Tickets & Documents
<!-- Any related info? -->


## Screenshots
<!-- Screenshots are nice :) -->



## How to test your change?
<!-- How should we test your change? -->


## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 Code comments
- [ ] 📕 Github pages
- [ ] 🚫 no documentation needed
```
